Update the README with new information.
Codertocat/Hello-World pull request #2
Opened 2019-05-15 15:20 UTC by Codertocat

This is a pretty simple change that we need to pull into master.

2019-05-15 15:21 UTC, closed without merging

2019-10-27 08:33 UTC, nmeum commented
Some Comment

2019-10-27 08:34 UTC, nmeum commented
Some Comment

2019-11-19 15:10 UTC, CarlosCondor commented on README.md
> -# Hello-World
asd

2019-12-06 15:39 UTC, johnpapa commented
From all of us on the Cloud Advocacy team at Microsoft, thank you @Codertocat for creating this pull request!

Have a Happy Holiday season!

2019-12-06 15:39 UTC, johnpapa commented
From all of us on the Cloud Advocacy team at Microsoft, thank you @Codertocat for creating this pull request!

Have a Happy Holiday season!

2020-01-08 13:18 UTC, carusogabriel approved these changes

2020-01-08 13:20 UTC, carusogabriel approved these changes

2020-07-11 10:41 UTC, jalallinux commented on README.md
> -# Hello-World
asd

2020-09-21 18:48 UTC, marcosapmf commented
ci:test:sf

2020-09-21 18:48 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 18:48 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 18:48 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 18:48 UTC, marcosapmf commented
ci:test:sf

2020-09-21 18:48 UTC, marcosapmf commented
ci:test:sf

2020-09-21 18:48 UTC, marcosapmf commented
ci:test:sf

2020-09-21 18:48 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:00 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:00 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:01 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:01 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:01 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:01 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:01 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:01 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:01 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:01 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:01 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:01 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:04 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:04 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:04 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:04 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:04 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:04 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:05 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:05 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:05 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:05 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:05 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:05 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:09 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:09 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:09 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:09 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:09 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:09 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:14 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:14 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:14 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:14 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:38 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:38 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 19:49 UTC, marcosapmf commented
ci:test:sf

2020-09-21 19:49 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:00 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:00 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:01 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:01 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:01 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:01 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:01 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:01 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:02 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:02 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:02 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:02 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:04 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:04 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:04 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:04 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:05 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:05 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:06 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:06 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:07 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:07 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:11 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:11 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:13 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:13 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:17 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:17 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:18 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:18 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:19 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:19 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:20 UTC, marcosapmf commented
ci:test:relevant

2020-09-21 20:20 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:21 UTC, marcosapmf commented
ci:test:sf

2020-09-21 20:21 UTC, marcosapmf commented
ci:test:relevant

2020-09-22 14:47 UTC, marcosapmf commented
ci:test:relevant

2020-09-22 14:47 UTC, marcosapmf commented
ci:test:sf

2021-04-09 13:22 UTC, acccrop commented
```
Error: This repo is not allowlisted for Atlantis.
```

2021-04-09 13:23 UTC, acccrop commented
```
Error: This repo is not allowlisted for Atlantis.
```

2021-12-23 08:54 UTC, svcosmghtest commented
@Codertocat, you must sign our contributor license agreement before your changes are merged. Click [here](https://d7d132ad.ngrok.io/cla/f594bed8ecfb482d96ae2cde3fa898d8) to sign the agreement. If you are a VMware employee, read [this](https://d7d132ad.ngrok.io/employee) for further instruction.

2021-12-27 20:59 UTC, allanwsilva commented
Hello, World!

2021-12-27 21:00 UTC, allanwsilva commented
Hello, World!

2021-12-27 21:01 UTC, allanwsilva commented
Hello, World!

2021-12-27 21:02 UTC, allanwsilva commented
Hello, World!

2021-12-27 21:02 UTC, allanwsilva commented
Hello, World!

2021-12-27 21:04 UTC, allanwsilva commented
Hello, World!

2022-03-23 04:51 UTC, svcosmghtest commented
@BennyThink, VMware has rejected your signed contributor license agreement. The merge can not proceed until the agreement has been resigned. Click [here](http://127.0.0.1:9000/cla/5fbc0d08d0a811ea87d00242ac131111) to resign the agreement.

2022-07-22 07:02 UTC, iAmNikola commented on README.md
> -# Hello-World
asd

2022-09-02 13:33 UTC, yemonerail commented
Yem was here!

2023-02-15 21:14 UTC, bbuxton93 requested changes
Load script test failed.
Log:
ReloadID: 63ed4b2583a3f98255ff416d
Started loading data
(A detailed script progress log can be downloaded when the reload is finished)
Data has not been loaded. Please correct the error and try loading again.
The following error occurred:
Unknown statement: Nobody reads
The error occurred here:
Nobody reads

2023-02-15 21:38 UTC, bbuxton93 requested changes
Load script test failed.
Log:
ReloadID: 63ed50ca83a3f98255ff44c3
Started loading data
(A detailed script progress log can be downloaded when the reload is finished)
Data has not been loaded. Please correct the error and try loading again.
The following error occurred:
Unknown statement: Nobody reads
The error occurred here:
Nobody reads

2023-09-19 12:43 UTC, jamesrenaud commented
### :robot: *Terraform Change Report*
---

### Change Summary

| Layer Name | Region | Creates | Updates | Deletes |
| :--- |  :--- | :---: | :---: | :---: |
| 20-bootstrap | | 0 | 14 | 0 |
| | uswest | 0 | 7 | 0 |
| | useast | 0 | 7 | 0 |


---

<!-- TFCHANGES START -->
### Terraform Changes

#### **20-bootstrap** ==> uswest
##### Plan: `0` to add, `7` to change, `0` to destroy

<details><summary>Show Plan</summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.monitoring.azurerm_resource_group.main_resource_group will be updated in-place
  ~ resource "azurerm_resource_group" "main_resource_group" {
        id       = "/subscriptions/0bf7eeee-63f3-4129-a0bc-b0424afc2633/resourceGroups/rg-kxs-sec-01"
        name     = "rg-kxs-sec-01"
      ~ tags     = {
          + "cat_business_unit" = "cloud_engineering"
          + "cat_environment"   = "shared"
          + "cat_owner"         = "ncuccia"
          + "created_by"        = "terraform"
        }
        # (1 unchanged attribute hidden)

        # (1 unchanged block hidden)
    }

  # module.backend.module.storage_account["stcsp2appeastustfstate"].azurerm_storage_account_network_rules.bootstrap will be updated in-place
  ~ resource "azurerm_storage_account_network_rules" "bootstrap" {
        id                         = "/subscriptions/34dbb730-7f89-4e5b-9102-dbc8fbb3b966/resourceGroups/rg-kxs-bootstrap-eastus-01/providers/Microsoft.Storage/storageAccounts/stcsp2appeastustfstate"
      ~ ip_rules                   = [
          - "20.121.20.179",
            # (5 unchanged elements hidden)
        ]
        # (4 unchanged attributes hidden)
    }

  # module.backend.module.storage_account["stcsp2cldeastustfstate"].azurerm_storage_account_network_rules.bootstrap will be updated in-place
  ~ resource "azurerm_storage_account_network_rules" "bootstrap" {
        id                         = "/subscriptions/34dbb730-7f89-4e5b-9102-dbc8fbb3b966/resourceGroups/rg-kxs-bootstrap-eastus-01/providers/Microsoft.Storage/storageAccounts/stcsp2cldeastustfstate"
      ~ ip_rules                   = [
          - "20.121.20.179",
            # (5 unchanged elements hidden)
        ]
        # (4 unchanged attributes hidden)
    }

  # module.backend.module.storage_account["stcsp2fweastustfstate"].azurerm_storage_account_network_rules.bootstrap will be updated in-place
  ~ resource "azurerm_storage_account_network_rules" "bootstrap" {
        id                         = "/subscriptions/34dbb730-7f89-4e5b-9102-dbc8fbb3b966/resourceGroups/rg-kxs-bootstrap-eastus-01/providers/Microsoft.Storage/storageAccounts/stcsp2fweastustfstate"
      ~ ip_rules                   = [
          - "20.121.20.179",
            # (5 unchanged elements hidden)
        ]
        # (4 unchanged attributes hidden)
    }

  # module.backend.module.storage_account["stcsp2infraeastustfstate"].azurerm_storage_account_network_rules.bootstrap will be updated in-place
  ~ resource "azurerm_storage_account_network_rules" "bootstrap" {
        id                         = "/subscriptions/34dbb730-7f89-4e5b-9102-dbc8fbb3b966/resourceGroups/rg-kxs-bootstrap-eastus-01/providers/Microsoft.Storage/storageAccounts/stcsp2infraeastustfstate"
      ~ ip_rules                   = [
          - "20.121.20.179",
            # (5 unchanged elements hidden)
        ]
        # (4 unchanged attributes hidden)
    }

  # module.backend.module.storage_account["stcsp2neteastustfstate"].azurerm_storage_account_network_rules.bootstrap will be updated in-place
  ~ resource "azurerm_storage_account_network_rules" "bootstrap" {
        id                         = "/subscriptions/34dbb730-7f89-4e5b-9102-dbc8fbb3b966/resourceGroups/rg-kxs-bootstrap-eastus-01/providers/Microsoft.Storage/storageAccounts/stcsp2neteastustfstate"
      ~ ip_rules                   = [
          - "20.121.20.179",
            # (5 unchanged elements hidden)
        ]
        # (4 unchanged attributes hidden)
    }

  # module.monitoring.module.loganalytics_workspace.azurerm_log_analytics_workspace.log_analytics_workspace will be updated in-place
  ~ resource "azurerm_log_analytics_workspace" "log_analytics_workspace" {
        id                              = "/subscriptions/0bf7eeee-63f3-4129-a0bc-b0424afc2633/resourceGroups/rg-kxs-sec-01/providers/Microsoft.OperationalInsights/workspaces/log-kxs-sec-apk-01"
        name                            = "log-kxs-sec-apk-01"
      ~ retention_in_days               = 90 -> 30
        tags                            = {
            "cat_business_unit" = "cloud_engineering"
            "cat_environment"   = "shared"
            "cat_owner"         = "ncuccia"
            "created_by"        = "terraform"
        }
        # (11 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 7 to change, 0 to destroy.

```
</details>

<details><summary>Show Diff</summary>

```diff
Index: module.backend.module.storage_account["stcsp2appeastustfstate"].azurerm_storage_account_network_rules.bootstrap
===================================================================
--- module.backend.module.storage_account["stcsp2appeastustfstate"].azurerm_storage_account_network_rules.bootstrap
+++ module.backend.module.storage_account["stcsp2appeastustfstate"].azurerm_storage_account_network_rules.bootstrap
@@ -4,9 +4,8 @@
 id: /subscriptions/34dbb730-7f89-4e5b-9102-dbc8fbb3b966/resourceGroups/rg-kxs-bootstrap-eastus-01/providers/Microsoft.Storage/storageAccounts/stcsp2appeastustfstate
 ip_rules:
   - 184.162.46.109
   - 184.95.211.82
-  - 20.121.20.179
   - 20.151.110.161
   - 45.61.8.148
   - 75.98.136.253
 private_link_access: []

```

```diff
Index: module.backend.module.storage_account["stcsp2cldeastustfstate"].azurerm_storage_account_network_rules.bootstrap
===================================================================
--- module.backend.module.storage_account["stcsp2cldeastustfstate"].azurerm_storage_account_network_rules.bootstrap
+++ module.backend.module.storage_account["stcsp2cldeastustfstate"].azurerm_storage_account_network_rules.bootstrap
@@ -4,9 +4,8 @@
 id: /subscriptions/34dbb730-7f89-4e5b-9102-dbc8fbb3b966/resourceGroups/rg-kxs-bootstrap-eastus-01/providers/Microsoft.Storage/storageAccounts/stcsp2cldeastustfstate
 ip_rules:
   - 184.162.46.109
   - 184.95.211.82
-  - 20.121.20.179
   - 20.151.110.161
   - 45.61.8.148
   - 75.98.136.253
 private_link_access: []

```

```diff
Index: module.backend.module.storage_account["stcsp2fweastustfstate"].azurerm_storage_account_network_rules.bootstrap
===================================================================
--- module.backend.module.storage_account["stcsp2fweastustfstate"].azurerm_storage_account_network_rules.bootstrap
+++ module.backend.module.storage_account["stcsp2fweastustfstate"].azurerm_storage_account_network_rules.bootstrap
@@ -4,9 +4,8 @@
 id: /subscriptions/34dbb730-7f89-4e5b-9102-dbc8fbb3b966/resourceGroups/rg-kxs-bootstrap-eastus-01/providers/Microsoft.Storage/storageAccounts/stcsp2fweastustfstate
 ip_rules:
   - 184.162.46.109
   - 184.95.211.82
-  - 20.121.20.179
   - 20.151.110.161
   - 45.61.8.148
   - 75.98.136.253
 private_link_access: []

```

```diff
Index: module.backend.module.storage_account["stcsp2infraeastustfstate"].azurerm_storage_account_network_rules.bootstrap
===================================================================
--- module.backend.module.storage_account["stcsp2infraeastustfstate"].azurerm_storage_account_network_rules.bootstrap
+++ module.backend.module.storage_account["stcsp2infraeastustfstate"].azurerm_storage_account_network_rules.bootstrap
@@ -4,9 +4,8 @@
 id: /subscriptions/34dbb730-7f89-4e5b-9102-dbc8fbb3b966/resourceGroups/rg-kxs-bootstrap-eastus-01/providers/Microsoft.Storage/storageAccounts/stcsp2infraeastustfstate
 ip_rules:
    [...]

2023-10-05 05:53 UTC, OppilaalDaniel requested changes
Reload failed.
Log:
ReloadID: 651e4f6332465c2bedda213f
Started loading data
(A detailed script progress log can be downloaded when the reload is finished)
Data has not been loaded. Please correct the error and try loading again.
The following error occurred:
Unknown statement: Nobody reads
The error occurred here:
Nobody reads

2023-10-05 05:59 UTC, OppilaalDaniel requested changes
Reload failed.
Log:
ReloadID: 651e50b19db56064f835bc0a
Started loading data
(A detailed script progress log can be downloaded when the reload is finished)
Data has not been loaded. Please correct the error and try loading again.
The following error occurred:
Unknown statement: Nobody reads
The error occurred here:
Nobody reads

2023-11-16 12:41 UTC, ftf-spn requested changes
ReloadID: 65560deac7d4e9dd5f54135f
Started loading data
(A detailed script progress log can be downloaded when the reload is finished)
Connected
Fact_Returns 6,214 Lines fetched

App saved
Finished successfully

2023-11-16 13:03 UTC, ftf-spn approved these changes

2024-03-18 10:39 UTC, Stan-Decoene-element61 requested changes
Load script test failed.
Log:
ReloadID: 65f819d8eaa235f9543d4be9
Started loading data
(A detailed script progress log can be downloaded when the reload is finished)
Data has not been loaded. Please correct the error and try loading again.
The following error occurred:
Unknown statement: Nobody reads
The error occurred here:
Nobody reads

2024-09-18 06:14 UTC, Onkar2u requested changes
Load script test failed.
Log:
ReloadID: 66ea6fae1b3109b1c84c0911
Started loading data
(A detailed script progress log can be downloaded when the reload is finished)
Data has not been loaded. Please correct the error and try loading again.
The following error occurred:
Unknown statement: Nobody reads
The engine error code: EDC_ERROR:11002
The error occurred here:
Nobody reads

2025-12-08 20:07 UTC, ChrFreese requested changes
Reload failed.
Log:
ReloadID: 6937301ae114ea1450e8ea76
Started loading data
(A detailed script progress log can be downloaded when the reload is finished)
Data has not been loaded. Please correct the error and try loading again.
The following error occurred:
Unknown statement: Nobody reads
The engine error code: Syntax error:11002
The error occurred here:
Nobody reads

2026-02-11 09:16 UTC, SudiptaDuttaIFZ requested changes
Reload failed.
Log:
ReloadID: 698c48f157c7ba58d0577a49
Started loading data
(A detailed script progress log can be downloaded when the reload is finished)
Data has not been loaded. Please correct the error and try loading again.
The following error(s) occurred:
Unknown statement: Nobody reads

2026-05-13 21:09 UTC, lindibeetge requested changes
Load script test failed.
Log:
ReloadID: 6a04e8a30f51bf589c8b440c
Started loading data
(A detailed script progress log can be downloaded when the reload is finished)
Data has not been loaded. Please correct the error and try loading again.
The following error(s) occurred:
Unknown statement: Nobody reads

2026-05-13 21:13 UTC, lindibeetge requested changes
Load script test failed.
Log:
ReloadID: 6a04e9620f51bf589c8b44b7
Started loading data
(A detailed script progress log can be downloaded when the reload is finished)
Data has not been loaded. Please correct the error and try loading again.
The following error(s) occurred:
Unknown statement: Nobody reads